### ISSUE TITLE
Using Java Service Bus should be reference from Windows Azure Java Developer Guide

### ISSUE THREAD

**Issue by gcheng** [Azure/azure-content#1142]
This page http://msdn.microsoft.com/en-us/library/windowsazure/hh690943(VS.103).aspx

should contain reference to the following pages 
http://www.windowsazure.com/en-us/develop/java/how-to-guides/service-bus-queues/
http://www.windowsazure.com/en-us/develop/java/how-to-guides/service-bus-topics/
![JavaServiceBusRef](https://f.cloud.github.com/assets/1541773/373897/0f840c76-a38f-11e2-9fac-96fc5c2adc8d.JPG)

**Comment by deneha** [comment]
@gcheng Thank you for the suggestion.  Since you are a MSFT employee, we ask that you use the GitHub capability to contribute to the article by submitting a change and a pull request through the process.  If you need guidance on how this works, please see the contributors guide here: https://github.com/Azure/azure-content-pr/blob/master/contributor-guide/contributor-guide-index.md
