### ISSUE TITLE
Using Service Bus Connection String instead of owner/secret

### ISSUE THREAD

**Issue by gcheng** [Azure/azure-content#1144]
Because of the globalization of the Azure, Java SDK no longer default to US instance because it is likely to cause global confusion. Instead, we support connection string, it will be great the how to guides can be updated accordingly 

http://www.windowsazure.com/en-us/develop/java/how-to-guides/service-bus-topics/

http://www.windowsazure.com/en-us/develop/java/how-to-guides/service-bus-queues/

it is recommended to use connection string and corresponding overloads instead. 

    /**
     * Creates a service bus configuration using the specified connection string.
     * @param profile
     *          A <code>String</code> object that represents the profile.
     * @param configuration
     *          A previously instantiated <code>Configuration</cone> object.
     * @param connectionString
     *          A <code>String</code> object the contains the connection string for the
     *          service bus connection information.
     * @return
     *         A <code>Configuration</code> object that can be used when creating an instance of the
     *         <code>ServiceBusService</code> class.
     */
    public static Configuration configureWithConnectionString(String profile, Configuration configuration,
        String connectionString) {

**Comment by deneha** [comment]
@gcheng Thank you for the suggestion.  Since you are a MSFT employee, we ask that you use the GitHub capability to contribute to the article by submitting a change and a pull request through the process.  If you need guidance on how this works, please see the contributors guide here: https://github.com/Azure/azure-content-pr/blob/master/contributor-guide/contributor-guide-index.md
