### ISSUE TITLE
On media service page, there should be a link to Java Service Bus how to

### ISSUE THREAD

**Issue by gcheng** [Azure/azure-content#1145]
Currently, it only has .NET at the bottom 

http://www.windowsazure.com/en-us/home/features/media-services/

**Comment by deneha** [comment]
@gcheng Thank you for the suggestion.  Since you are a MSFT employee, we ask that you use the GitHub capability to contribute to the article by submitting a change and a pull request through the process.  If you need guidance on how this works, please see the contributors guide here: https://github.com/Azure/azure-content-pr/blob/master/contributor-guide/contributor-guide-index.md
