### ISSUE TITLE
Update the Big Data portion in [Data Services](http://www.windowsazure.com/en-us/develop/net/data/)

### ISSUE THREAD

**Issue by mumian** [Azure/azure-content#1151]
The two tutorials under the Big Data section are not relevant.

I suggest to list the following two articles instead:

Guidance: Introduction to the Windows Azure HDInsight Service

          A conceptual overview of the components of HDInsight.

Tutorial: Get Started with the HDInsight Service

           Learn the fundamentals of working with the HDInsight service.

**Comment by deneha** [comment]
@mumian Thank you for the suggestion.  Since you are a MSFT employee, we ask that you use the GitHub capability to contribute to the article by submitting a change and a pull request through the process.  If you need guidance on how this works, please see the contributors guide here: https://github.com/Azure/azure-content-pr/blob/master/contributor-guide/contributor-guide-index.md
