### ISSUE TITLE
Update a paragraph in [Best Practices for Performance in Windows Azure Applications](http://www.windowsazure.com/en-us/develop/net/best-practices/performance/)

### ISSUE THREAD

**Issue by mumian** [Azure/azure-content#1152]
The following paragraph needs to be updated:

Windows Azure provides direct support for Hadoop, and also enables use of other technologies. For information about Hadoop on Windows Azure, see:

[Apache Hadoop-based Services for Windows Azure]
[Big Data]
[Big Data Hadoop Preview Comes to Windows Azure]

with 

Windows Azure HdInsight Service provides direct support for Hadoop, and also enables use of other technologies. For information about HDInsight see:

[Windows Azure HDInsight Service](http://www.windowsazure.com/en-us/manage/services/hdinsight/)
[Big Data](http://www.windowsazure.com/en-us/home/scenarios/big-data/)
[Tutorial: Getting Started with the Windows Azure HDInsight Service](http://www.windowsazure.com/en-us/manage/services/hdinsight/get-started-hdinsight/)

**Comment by deneha** [comment]
@mumian Thank you for the suggestion.  Since you are a MSFT employee, we ask that you use the GitHub capability to contribute to the article by submitting a change and a pull request through the process.  If you need guidance on how this works, please see the contributors guide here: https://github.com/Azure/azure-content-pr/blob/master/contributor-guide/contributor-guide-index.md
