### ISSUE TITLE
PHP should be mentioned in the service bus documentation

### ISSUE THREAD

**Issue by gcheng** [Azure/azure-content#1171]
http://www.windowsazure.com/en-us/home/features/messaging/

![phpservicebus](https://f.cloud.github.com/assets/1541773/398391/5c20964a-a857-11e2-87ee-3bfd493ad7d3.png)

**Comment by deneha** [comment]
@gcheng Thank you for the suggestion.  Since you are a MSFT employee, we ask that you use the GitHub capability to contribute to the article by submitting a change and a pull request through the process.  If you need guidance on how this works, please see the contributors guide here: https://github.com/Azure/azure-content-pr/blob/master/contributor-guide/contributor-guide-index.md
