### ISSUE TITLE
chaining service bus with auto forwarding is not clickable. 

### ISSUE THREAD

**Issue by gcheng** [Azure/azure-content#1249]
Although it appears to be clickable like other blue text, but actually it is not on chrome browser 

http://msdn.microsoft.com/en-us/library/windowsazure/jj737688.aspx

![sbchain](https://f.cloud.github.com/assets/1541773/445271/242c91d4-b1b8-11e2-89d9-c55ebe7f9076.jpg)

**Comment by deneha** [comment]
@gcheng Thank you for the suggestion.  Since you are a MSFT employee, we ask that you use the GitHub capability to contribute to the article by submitting a change and a pull request through the process.  If you need guidance on how this works, please see the contributors guide here: https://github.com/Azure/azure-content-pr/blob/master/contributor-guide/contributor-guide-index.md
