### ISSUE TITLE
The URI of the POST request is incorrect

### ISSUE THREAD

**Issue by gcheng** [Azure/azure-content#1258]
http://msdn.microsoft.com/en-us/library/jj839746.aspx

there should be subscription/topic there instead of queue.

**Comment by deneha** [comment]
@gcheng Thank you for the suggestion.  Since you are a MSFT employee, we ask that you use the GitHub capability to contribute to the article by submitting a change and a pull request through the process.  If you need guidance on how this works, please see the contributors guide here: https://github.com/Azure/azure-content-pr/blob/master/contributor-guide/contributor-guide-index.md
