### ISSUE TITLE
service bus configuration links do not distinguish from each other. 

### ISSUE THREAD

**Issue by gcheng** [Azure/azure-content#1270]
All the "CreateFromConnectionString" links should distinguish from each other because they all link to different pages
![configurationconnectionstring](https://f.cloud.github.com/assets/1541773/455736/6069a7e8-b359-11e2-852b-0569d752e159.jpg)
.

**Comment by deneha** [comment]
@gcheng Thank you for the suggestion.  Since you are a MSFT employee, we ask that you use the GitHub capability to contribute to the article by submitting a change and a pull request through the process.  If you need guidance on how this works, please see the contributors guide here: https://github.com/Azure/azure-content-pr/blob/master/contributor-guide/contributor-guide-index.md
