### ISSUE TITLE
http://www.windowsazure.com/en-us/downloads/

### ISSUE THREAD

**Issue by mumian** [Azure/azure-content#1470]
I found this page a bit confusing. 

* The default is Mobile services.  What I expect are two dedicated pages for "Languages" and "Services", on which there are list of languages and services and some brief descriptions.  The default will be either Languages or Services.

* Languages and Services are the two categories. They are in bold, but still not clear enough for me.  You might consider using indentation or bigger font size to  make them standing out.

* Under Resources for each language and service, there is a "Get started tutorial".  Because the blue banner "Downloads, Get the command-line tools and SDKs you need. Fast." take the most dominant position. I got the impression that tutorial is for the command-line tools and SDK instead of for specific language or service.  For example,  instead of saying "Get started tutorial" under Mobile, say "Get started with Mobile Services".

**Comment by deneha** [comment]
@mumian Thank you for the suggestion.  Since you are a MSFT employee, we ask that you use the GitHub capability to contribute to the article by submitting a change and a pull request through the process.  If you need guidance on how this works, please see the contributors guide here: https://github.com/Azure/azure-content-pr/blob/master/contributor-guide/contributor-guide-index.md
