### ISSUE TITLE
AMQP Feature Guide returns 404 on Azure

### ISSUE THREAD

**Issue by Injac** [Azure/azure-content#2088]
Hi, 
for this article:
https://github.com/Azure/azure-content/blob/master/articles/service-bus-dotnet-advanced-message-queuing.md
The link on azure.com returns a 404 (section App Services, Link name: Service Bus AMQP feature guide ):
http://azure.microsoft.com/en-us/develop/net/

**Comment by deneha** [comment]
@Injac Thank you for raising this issue.  We're sorry for the delay in response.  It looks like the issue has been resolved from my end.  Please let me know if it persists for you.  

We're reviewing old issues and closing them. If this issue should not be closed, please let us know so that we can reopen it and assign it to the proper person.
