### ISSUE TITLE
other Azure Services are not allowed access to the Server's databases.

### ISSUE THREAD

**Issue by nileshkrishnan** [Azure/azure-content#2230]
•If you create a new Azure SQL Database on an existing Azure SQL Server, the firewall rules of the Server are not changed. As a result, it's possible other Azure Services are not allowed access to the Server's databases.

do we have any workaround on this if yes, can we add

**Comment by deneha** [comment]
@jeffgoll Can you assist?  Sent mail.

**Comment by jeffgoll** [comment]
@deneha not sure what the expectation is here, whether the customer is monitoring this thread, or in what context the issue was logged. But the behavior described is by design. The workaround, in general, I believe would be to leave the server level firewall rule least restrictive, and then enable DB-level firewall rules. But I say that without being aware of the specific security requirements, app requirements, and threat assessment. There is a topic on MSDN https://msdn.microsoft.com/en-us/library/azure/ee621782.aspx that might help the reader.
