### ISSUE TITLE
HTML Mobile Services with .NET Backend docs

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-content#2690]
There seems to be no documentation for mobile services HTML client with .NET backend. Is this due to limitations of the client?

Also now that the ADAL JS library is now GA does this add these capabilities? (I.e. We use ADAL iOS for auth on iOS, does this library now enable the same flow)

http://blogs.technet.com/b/ad/archive/2015/02/19/adal-javascript-v1-reaches-ga.aspx

**Comment by ggailey777** [comment]
HTML/JavaScript clients, including Cordova clients, are supported in the .NET backend, we just haven't had time to create tutorials specifically for this scenario. We had also made some assumptions that folks writing JavaScript apps would most likely use the Node.js backend rather than .NET. 
There is a quickstart project that you can download from the Azure portal that has both the .NET backend project and an HTML/JavaScript app project.

![html-dotnet-quickstart](https://cloud.githubusercontent.com/assets/1388263/7084604/d195aaaa-df23-11e4-86d3-989939287670.PNG)

I would assume that the ADAL JS library would also work, but I have never tried it. I'll try to get someone else to respond to this thread who would know for sure.

**Comment by damienpontifex** [comment]
I was particularly having issues authenticating against Azure AD. The actual flow of data is all fine, but considering the other (e.g. [iOS authentication](http://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-dotnet-backend-ios-aad-sso-preview/)) SDKs required authenticating against Azure AD and then sending the token to my mobile service I was wondering whether this is the same pattern required for the HTML client?

**Comment by mattchenderson** [comment]
This should work - it's not a documented scenario yet, and I can't say that I've tried it myself, but conceptually this should work. I want to point out that there are some major differences between the JS ADAL and the others. For example. I don't believe you can get a multi-resource refresh token. Content-wise, it might be good to address this one just because of the uniqueness. Likely it would show up under Mobile Apps, and after we get the other ADAL tutorials in line.
