### ISSUE TITLE
Code example bug in storage-dotnet-how-to-use-tables when describing how to read the connection string

### ISSUE THREAD

**Issue by buzzfrog** [Azure/azure-content#2968]
If you follow the instructions in the section **Configuring your connection string using .NET configuration** the code example under section **Retrieving your connection string** will not work.

    CloudStorageAccount storageAccount = CloudStorageAccount.Parse(ConfigurationManager.ConnectionStrings["StorageConnectionString"].ConnectionString);

The right code should be:

    CloudStorageAccount storageAccount = CloudStorageAccount.Parse(ConfigurationManager.AppSettings["StorageConnectionString"]);

Tested in a ASP.NET MVC Project.

**Comment by tysonn** [comment]
Hi Dag - could you please close this issue and contribute the correction directly into the article, please? Thanks

**Comment by deneha** [comment]
@buzzfrog  Thank you for the suggestion.  Since you are a MSFT employee, we ask that you use the GitHub capability to contribute to the article by submitting a change and a pull request through the process.  If you need guidance on how this works, please see the contributors guide here: https://github.com/Azure/azure-content-pr/blob/master/contributor-guide/contributor-guide-index.md
