### ISSUE TITLE
Links with https://www.windowsazure.com/develop base go to 404.

### ISSUE THREAD

**Issue by seanfreiburg** [Azure/azure-content#3035]
It appears many links are still under https://www.windowsazure.com/develop and the 3 I have found so far all 404. It looks like they just need to be updated.

**Comment by deneha** [comment]
@seanfreiburg Thank you for the suggestion.  Since you are a MSFT employee, we ask that you use the GitHub capability to contribute to the article by submitting a change and a pull request through the process.  If you need guidance on how this works, please see the contributors guide here: https://github.com/Azure/azure-content-pr/blob/master/contributor-guide/contributor-guide-index.md
