### ISSUE TITLE
Link to "How to Log on to a Virtual Machine Running Windows Server" goes to 404

### ISSUE THREAD

**Issue by spatnaik** [Azure/azure-content#3038]
Correct link is http://azure.microsoft.com/en-us/documentation/articles/virtual-machines-log-on-windows-server/

**Comment by deneha** [comment]
@spatnaik Thank you for the suggestion.  Since you are a MSFT employee, we ask that you use the GitHub capability to contribute to the article by submitting a change and a pull request through the process.  If you need guidance on how this works, please see the contributors guide here: https://github.com/Azure/azure-content-pr/blob/master/contributor-guide/contributor-guide-index.md
