### ISSUE TITLE
Port confusion on integration-hybrid-connection-overview.md?

### ISSUE THREAD

**Issue by naughton** [Azure/azure-content#3153]
The document says:

"9352	Used to push and pull data. If TCP port 9352 is unavailable, TCP port 443 is used."

However, I captured packets while starting HCM and saw the following:

1)      TLS Client Handshake outbound to 168.62.16.180:443.  Nine packets were exchanged and then the connection closed.
2)      Service Bus Relay outbound to 168.62.16.180:9350.  Seven packets were exchanged and then the connection closed.
3)      Hybrid Connection outbound to 168.62.16.180:5671.  This socket stays open while HCM is running.

Note that I saw no connections over 9352 at all and the document makes no reference to 9350 at all.

In environments where ALL outbound traffic is denied except by exception, it would be nice if this document explicitly enumerated the ports that should be opened to enable HC without using the fallback 443.  And also an explanation of why it is bad to fallback to 443.  Performance?

Reference this document: https://msdn.microsoft.com/en-us/library/azure/ee732535.aspx for even less clear explanation of the port usage for SBR.  It seems 9350 is TransportSecurityNone OneWay?

**Comment by deneha** [comment]
@naughton Thank you very much for this suggestion.  We would like to invite you to contribute directly to the article via the GitHub contribution functionality.

**Comment by naughton** [comment]
I would be happy to contribute to the document if someone from Microsoft would answer the questions regarding the use of port 9350-9353.  There should also be a section on what is required to make HCM work effectively through a web proxy.   The service bus endpoints delivered in the atom file are listed by IP address, which means that outbound firewall rules must allow the whole range of public Azure IP addresses... https://www.microsoft.com/en-us/download/details.aspx?id=41653   Is this not the right forum to get the Azure team's input?

**Comment by ChrisCompy** [comment]
To answer your questions: 

*1) TLS Client Handshake outbound to 168.62.16.180:443. Nine packets were exchanged and then the connection closed.*
**It’s common to get the ACS token over SSL.**

*2) Service Bus Relay outbound to 168.62.16.180:9350. Seven packets were exchanged and then the connection closed.*
**This is the relay binding making a “probe” attempt over port 9350 to see if “TCP” mode will work.  If port 9350 works, then 9350-9352 and 5671 are assumed to be allowed and “TCP” mode is used.**

*3) Hybrid Connection outbound to 168.62.16.180:5671. This socket stays open while HCM is running*
**Underneath it all the HCM uses some technology from Azure Service Bus and starting with the Service Bus SDK 2.3, in “TCP” mode a relay listener’s “control channel” uses port 5671 while the “data channels” which get created when clients connect operate over port 9352**

Hope that answers your questions and sorry about how long it took to get back to you.

**Comment by deneha** [comment]
@naughton Has your question been answered?  We'll leave this issue open for another week to see if you need additional help.

**Comment by naughton** [comment]
Not really.

What are the use cases of the three ports: 9350-9352?

Also, can you address what happens if these ports aren't open?

Also, can you address what the destination addresses are for all these connections?

For systems with outbound firewall rules in place, what needs to be opened?

**Comment by ChrisCompy** [comment]
**Q: What are the use cases of the three ports: 9350-9352?**
A: These ports are used for data transmission.  The relay manager will probe out on port 9350 to determine if TCP connectivity is available.  If it is available then it assumes that port 9352 is also available and data traffic will go over port 9352  When this is the case then Port 5671 is used for a control channel.  

**Q: Also, can you address what happens if these ports aren't open?**
A:  If ports 9350-9352 are not usable to access Azure then it should fall back to using port 443 for data transmission as well as the control channel.  

**Q: Also, can you address what the destination addresses are for all these connections?**
A:  The destinations resolve to Azure Service Bus relay service endpoints.  The list of IPs used is not fixed.  There is no current way to reserve a static IP for this either.

**Q: For systems with outbound firewall rules in place, what needs to be opened?**
A: Ports 80, and 443 are required.  Ports 5671 and 9350-9352 are a set as it were and are all used together.  

**Q: Why is it not recommended to fall back to port 443?**
A: Falling back to port 443 hits performance because then Http/Websocket is used as the protocol instead of native TCP for data channels.  This results in lower performance.

**Comment by MandiOhlinger** [comment]
These are good questions. In this topic, I added more details to the TCP Ports table; which should be public on Tuesday June 8.

**Comment by deneha** [comment]
@naughton The issue appears to have been corrected. We're closing this issue. Please comment if you need the issue to be reopened for any reason.  We'll be happy to assist you further if this resolution has not solved the issue.

**Comment by gauravdhamija83** [comment]
@MandiOhlinger In documentation section [Hybrid Connections - Security and Ports](https://azure.microsoft.com/en-us/documentation/articles/integration-hybrid-connection-overview/#security-and-ports), in the first row it still says that Port "9350 - 9354" are recommended to be opened for outbound communication. Shouldn't it be "9350, 9352" as only these two ports are required?
