### ISSUE TITLE
several links on Azure Logic Apps are missing

### ISSUE THREAD

**Issue by johnnliu** [Azure/azure-content#3172]
Logic App Workflow Management API
http://go.microsoft.com/fwlink/?LinkID=525617&clcid=9

Logic App Workflow Definition Language
http://go.microsoft.com/fwlink/?LinkID=529171&clcid=9

Logic App Workflow Triggers and Actions
http://go.microsoft.com/fwlink/?LinkID=529172&clcid=9

These three links are pretty important to figure out what other Template Language Expression functions we can use.

**Comment by deneha** [comment]
@johnnliu Thank you for the suggestion.  Since you are a MSFT employee, we ask that you use the GitHub capability to contribute to the article by submitting a change and a pull request through the process.  If you need guidance on how this works, please see the contributors guide here: https://github.com/Azure/azure-content-pr/blob/master/contributor-guide/contributor-guide-index.md
