### ISSUE TITLE
Appcelerator articles deleted

### ISSUE THREAD

**Issue by rpiwetz** [Azure/azure-content#3787]
I was following along on 2 Appcelerator tutorials yesterday that were hosted here.  They both seem to have been deleted.

https://github.com/Azure/azure-content/blob/master/articles/partner-appcelerator-mobile-services-javascript-backend-appcelerator-get-started.md

https://github.com/Azure/azure-content/blob/master/articles/partner-appcelerator-mobile-services-javascript-backend-appcelerator-get-started-users.md

**Comment by deneha** [comment]
@rpiwetz Thanks for raising the issue!  I'll find someone who can help figure out what happened here.

**Comment by ggailey777** [comment]
Sorry for the delayed response. We pull these tutorials because they were authored by Appcelerator and we could no longer get them to work as written. We could not get Appcelerator to update them. Sorry again for the inconvenience. We are currently working on a new HTML library for Azure Mobile Apps, which will have better support for JavaScript platforms, such as Cordova, ionic, and hopefully also Appcelerator. Please keep an eye out for details on the [Azure blog](https://azure.microsoft.com/en-us/blog/topics/mobile/).
