### ISSUE TITLE
Article has no parent category or navigation

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-content#4089]
https://azure.microsoft.com/en-us/documentation/articles/resource-group-advanced-template/

this article seems very alone. I googled this and came across this page, now I want to discover more articles like this to learn more about Resource Group Templates however I can't, because the sidebar is empty and I cannot navigate to the category this belongs to.

For instance this article has a proper navigation: https://azure.microsoft.com/en-us/documentation/articles/resource-group-template-functions/#next-steps

cc: @tfitzmac

**Comment by ahmetalpbalkan** [comment]
Also "Edit on Github" link on this page is a 404.

**Comment by deneha** [comment]
@ahmetalpbalkan Thanks for reporting these issues.  The 404 issue has been escalated.

@tfitzmac Can you assist?

**Comment by tfitzmac** [comment]
@ahmetalpbalkan thanks for the feedback about this topic. The content from this topic was recently moved into two new topics - https://azure.microsoft.com/en-us/documentation/articles/resource-group-create-multiple/ and https://azure.microsoft.com/en-us/documentation/articles/resource-group-linked-templates/

After I get a redirect set up, I am going to delete the original topic which is why it is not connected to the left nav for Azure Resource Manager.

**Comment by tfitzmac** [comment]
@ahmetalpbalkan - the redirect has been set up and the old topic deleted. The previous link now goes to the new topic. I believe this issue can be closed.

**Comment by ahmetalpbalkan** [comment]
thanks
