### ISSUE TITLE
Elastic Database client library with Entity Framework - Open Connection issues

### ISSUE THREAD

**Issue by stevozilik** [Azure/azure-content#4144]
Hi,

I've been playing around with the ShardMapManager and provisioning connections for DbContext, and I believe that the two don't play together well. Specifically the fact that you have to open the connection immediately when the DbContext is created, as opposed to lazy opening when it is first needed.

Ultimately this comes down to the fact that there can be long running processes between the DbContext creation and the first 'query', when the connection is open, but not used. This can lead to the connection timing out, or the shard changing state and invalidating the connection (which is open for no reason). This changes the behavior of Entity Framework and (silently) introduces unnecessary issues.

Is there another approach we can take for EntityFramework to behave as before? I've gone as far as creating custom DbConnection, DbProviderFactory, DbCommand wrapping the Sql counterparts, but that is going just deeper and deeper into the rabbit hole, not being able to resolve casting conflicts in sealed Sql Db classes.

Any ideas? :)
Stevo

**Comment by tysonn** [comment]
@sidneyh & @JennieHubbard - Jenny and Sidney, could you look at this?

**Comment by sidneyh** [comment]
Cc’ing the PM team.

**Comment by sidneyh** [comment]
cc'ing the PM team via GitHub:
@torsteng @tysonn @JennieHubbard @SilviaDoomra

**Comment by torsteng** [comment]
Hi Stevo,

The Elastic Database library performs a couple of things on the connection before it is returned. These steps include validating that the sharding key you asked for is still present on that shard. The library will also spin up the infrastructure to close the connection if the sharding key and its dependent data are being moved while the connection is open. These checks are performed using T-SQL and therefore require an open connection. This is the reason why the library always returns an open connection. 

Working with open SQL connections is well-supported through the EF DbContext constructors that we are using. And just to clarify - we are not making any changes to the behavior of EF in order to work with open SQL connections.

I do agree with your concern that you don't want open SQL connections around for extended periods of time. There are various reasons for this and you mention some of the key ones. Based on this, we do encourage creating the DbContext as late as possible and to avoid blocking when a DbContext is around, e.g., for receiving user input. 

Hope this helps.

Thanks,
Torsten

**Comment by sidneyh** [comment]
I have posted a reply.

From: Sidney Higa
Sent: Monday, August 3, 2015 9:35 AM
To: Azure/azure-content <reply@reply.github.com>; Azure/azure-content <azure-content@noreply.github.com>
Cc: Debra Dove <ddove@microsoft.com>; Torsten Grabs <torsteng@microsoft.com>; Silvia Doomra <sdoomra@microsoft.com>; Stuart Ozer <stuarto@microsoft.com>
Subject: RE: [azure-content] Elastic Database client library with Entity Framework - Open Connection issues (#4144)

Cc’ing the PM team.

**Comment by stevozilik** [comment]
Hi Torsten,

appreciate quick response.

I agree with what you are doing besides opening the connection, I think it's great, but the issue is when is it happening.

With the existing examples and guidance, some applications including mine will behave differently. I've designed my application knowing how EF works with database connections by default, taking advantage of it, and now that's not the case anymore.

I think at least you should give a choice to be able to maintain the default connection handling with EF, either by modifying the ShardMap Api (e.g. by exposing a method to perform the checks you mentioned above explicitly, putting the responsibility on client code to call it when connection is open), or providing an example on how this can be done with the current API (I could not figure it out, but maybe there is a way)..

I'm sure that all this can be implemented to keep the existing EF connections behavior, it's just a matter of handling it differently in the ShardMap Api. From my perspective there is no doubt that what you're are doing is good for us, potentially preventing calling code from trying to access data that has been moved elsewhere and thus failing. But with current implementation, by removing a potential issue (which is arguably not very frequent  - updating shard map), you are introducing a different potential issue which in my case is going to be much more frequent. 

Without knowing any details, why not subscribing to the connection 'StateChanged' event and doing your checks on 'Open'? You still have a reference to the connection and can close it if you detect anything invalid, and enable calling code to open the connection as required. 

Thanks for consideration,
Stevo

**Comment by stevozilik** [comment]
Hi Guys,

I've build my application around Federations and Entity Framework lazy connection opening, passing DbContext around for better performance and to workaround the lack of distributed transactions, still having well separated code in small units.

You've retired the first and crippled the second, that is not a recipe for success. Are you expecting me to refactor all my data access logic?

I really would appreciate some help on this. The technology is meant to be moving ahead, not backwards.

Regards,
Stevo

**Comment by torsteng** [comment]
Hi Stevo,

Thanks for the continued feedback and for sharing your concerns. We have discussed the kind of support for Entity Framework that you need in the Elastic Database client library with the EF team. This would be a major work item – and the investment would be limited to just EF. Rather than making a large investment just for EF, we would like to make one investment that lights up other ORMs (Dapper, nHibernate etc.), other languages (Java, Php), and other protocols (ODBC, JDBC). We have decided to focus on that latter investment which enables the broader set of capabilities. It will surface a regular SQL Server connection rather than specialized client-side APIs. You can see the beginnings of that effort in our capabilities around Elastic Database Query (https://azure.microsoft.com/en-us/documentation/articles/sql-database-elastic-query-overview/) which works through a regular SQL Server connection endpoint that can also be used for EF. It works for read-only scenarios. Completing this to also include DML is a sizeable amount of engineering work. That’s the reason why it is not yet ready and what we propose has the intent to unblock you (or other EF customers) for DML. Once the Elastic Query work I outlined is complete, it will allow you to use your regular DbContexts in EF over a scaled out data tier in SQLDB and pass your contexts around as you need.

Hope this makes sense.

Thanks,
Torsten

**Comment by tysonn** [comment]
@stevozilik - Thanks for filing this. Based on the thread, it looks like the team has responded, so I'm going to close.
