### ISSUE TITLE
Problem with Reliable Actors design pattern: distributed computation article

### ISSUE THREAD

**Issue by DesrosiersC** [Azure/azure-content#4195]
Hi,

There seems to be an inconsistency in the Reliable Actors design pattern: distributed computation article. The graphic and text is stating that the Aggregator should be stateless and have multiple concurrent instances but the code tells a different story.

Since the Aggregator inherits from "Actor of (AggregatorState)", it is statefull. Now, since it is always created by PooledTask with an Id of 0, there will always be only one instance.

**Comment by deneha** [comment]
@DesrosiersC Thank you for raising this issue.  Do you have the link to this article?

**Comment by DesrosiersC** [comment]
@deneha Here it is:
https://github.com/Azure/azure-content/blob/master/articles/service-fabric/service-fabric-reliable-actors-pattern-distributed-computation.md

**Comment by deneha** [comment]
@DesrosiersC Thanks!  I'll contact a member of our team to review your question.

@jessebenson Could you please assist?

**Comment by clca** [comment]
Thanks for reporting this issue. There is a small inconsistency in the code snippet. Instead of using the same Id, aggregator should be created using a unique ID:
        var agg = ActorProxy.Create<IAggregator>(ActorId.NewId());

**Comment by DesrosiersC** [comment]
Just trying to understand here. If every Aggregator is created wit a different ID, doesn't that mean that each task will end up creating it's own Aggregator ? If that's the case, they won't aggregate much...
This is not what is illustrated in the graphic.

**Comment by Robbert-Driven-It** [comment]
Hi guys, I was looking for a way to comment on the distributed-computation article and I found this thread. I'm glad I'm not the only one having some problems getting my head around the sample code. 
one of the first questions I have is what is the significants of this call, 
'var task = ActorProxy.Create<IPooledTask>(0);'
does the id 0 do anything special? or is it simply pointing to the same instance of a PooledTask actor (with id 0) and calling it's 'CalculateAsync' method multiple times in parallel.
This actually raises another question, because I understood the Turn-based concurrency prevented such parallel calls and would queue the calls and process them in a single threaded fashion.. which would clearly defeat the whole purpose so I must be missing something.
If I assume 'var task = ActorProxy.Create<IPooledTask>(0);' actually gives you multiple actors(when called multiple times) then I end up with the same question DesrosiersC recently posed; if each PooledTask actor creates an Aggregator with a different Id how is the aggregation actually taking place?

**Comment by DesrosiersC** [comment]
My understanding is that it depends on whether the actor is statefull or stateless. If it is stateless, you'll have multiple instances even if you use Id 0 for each call.

It still doesn't answer my first question: is the aggregator statefull or not ? And if it is statefull, how does the sample actually work ?

I guess @jessebenson would be the best to answer us but I do get it that he must be busy.

**Comment by jessebenson** [comment]
I've updated the article to match the image.  The code should be creating 'taskCount' unique stateless IPooledTask actors, which each attempt to calculate Pi.  These pooled actors should send their results to a smaller number of stateful IAggregator actors, which accumulate the result and save it.  The aggregator actors send the final results to the single IFinaliser actor that accumulates the final estimate and displays it.  In the code snippet, the aggregator starts a 5-second repeating Timer to fire "ProcessAsync" to send new estimates to the finaliser (if it has any new estimates - see its "_pending" field).

**Comment by DesrosiersC** [comment]
Thanks @jessebenson, I really appreciate that you took the time to take a look. Hope it will help others like me to understand better that wonderful new platform.

**Comment by jessebenson** [comment]
For both stateless and stateful actors, the ActorId is the way to get a reference to an actor instance.  So the Id 0 will refer to the same actor instance for both stateless and stateful.

**Comment by DesrosiersC** [comment]
@jessebenson thanks for the precision.

The following phrase in the article was confusing to me:
----
We are using stateless actors for two main reasons: the runtime will decide how many aggregators are needed dynamically, therefore giving us scale on demand; and it will instantiate these actors “locally” – in other words in the same silo of the calling actor, reducing network hops.
----
I thought that when using stateless actors, the notion of instance was much more flexible and that the runtime would create some locally on demand.

**Comment by jessebenson** [comment]
@clca - can you help clarify the comment about instantiating actors "locally"?

**Comment by Robbert-Driven-It** [comment]
Thanks for updating the article makes a lot more sense now
