### ISSUE TITLE
Need more documentation for using Java Service Runtime

### ISSUE THREAD

**Issue by jcookems** [Azure/azure-content#991]
See https://github.com/WindowsAzure/azure-sdk-for-java/issues/239 for more details. The Java dev center talks about how to use the Service Runtime when deploying with the "Windows Azure Plugin for Eclipse with Java", but does not talk about other types deployment scenarios. Should add a topic with content along the lines of @gcheng answer in http://stackoverflow.com/questions/9415237/java-sdk-for-azure-error-with-roleenvironment-getcurrentroleinstance/14900834#14900834

**Comment by deneha** [comment]
@jcookems Thank you for the suggestion.  Since you are a MSFT employee, we ask that you use the GitHub capability to contribute to the article by submitting a change and a pull request through the process.  If you need guidance on how this works, please see the contributors guide here: https://github.com/Azure/azure-content-pr/blob/master/contributor-guide/contributor-guide-index.md
